spring:
  profiles:
    active: dev
  application:
    name: register
server:
  port: 7500
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:7500/eureka/

